### ISSUE TITLE
fatal: Failed to create PAT

### ISSUE THREAD

**Issue by TamasSzerb** [GitCredentialManager/git-credential-manager#1006]
git clone [redacted]:

in browser: "Authentication complete. You can return to the application. Feel free to close this browser tab."

fatal: Failed to create PAT

with GCM_TRACE=1 git clone

13:59:00.402931 ...DevOpsRestApi.cs:128 trace: [CreatePersonalAccessTokenAsync] HTTP: Response 403 [Forbidden]
fatal: Failed to create PAT
   at Microsoft.AzureRepos.AzureDevOpsRestApi.CreatePersonalAccessTokenAsync(Uri organizationUri, String accessToken, IEnumerable`1 scopes)
   at Microsoft.AzureRepos.AzureReposHostProvider.GeneratePersonalAccessTokenAsync(InputArguments input)
   at Microsoft.AzureRepos.AzureReposHostProvider.GetCredentialAsync(InputArguments input)
   at GitCredentialManager.Commands.GetCommand.ExecuteInternalAsync(InputArguments input, IHostProvider provider)
   at GitCredentialManager.Commands.GitCommandBase.ExecuteAsync()
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by ldennington** [comment]
Are you able to access this repo in your browser?

**Comment by TamasSzerb** [comment]
Without any issue.

**Comment by ldennington** [comment]
Ok, can you please provide the following information:

1. What version of GCM are you using (run `git-credential-manager-core --version`)?
2. What output, if any, do you see when you run `git config --get credential.azreposCredentialType`?
3. Can you include the additional `TRACE` information surrounding the error?

**Comment by TamasSzerb** [comment]
1. git-credential-manager-core --version
warning: git-credential-manager-core was renamed to git-credential-manager
warning: see https://aka.ms/gcm/rename for more information
2.0.886+ea93cb5158
2. git config --get credential.azreposCredentialType # nothing returned
3. git clone:
23:28:34.323346 ...DevOpsRestApi.cs:167 trace: [GetIdentityServiceUriAsync] HTTP: GET https://dev.azure.com/1A4D/_apis/ServiceDefinitions/LocationService2/[REDACTED UUID]?api-version=1.0
23:28:35.562455 ...DevOpsRestApi.cs:171 trace: [GetIdentityServiceUriAsync] HTTP: Response 200 [OK]
23:28:35.565998 ...DevOpsRestApi.cs:119 trace: [CreatePersonalAccessTokenAsync] Identity Service endpoint is 'https://spsprodcus3.vssps.visualstudio.com/[REDACTED UUID]/'.
23:28:35.566058 ...DevOpsRestApi.cs:123 trace: [CreatePersonalAccessTokenAsync] HTTP: POST https://spsprodcus3.vssps.visualstudio.com/[REDACTED UUID]/_apis/token/sessiontokens?api-version=1.0&tokentype=compact
23:28:36.665358 ...DevOpsRestApi.cs:128 trace: [CreatePersonalAccessTokenAsync] HTTP: Response 403 [Forbidden]
fatal: Failed to create PAT
   at Microsoft.AzureRepos.AzureDevOpsRestApi.CreatePersonalAccessTokenAsync(Uri organizationUri, String accessToken, IEnumerable`1 scopes)
   at Microsoft.AzureRepos.AzureReposHostProvider.GeneratePersonalAccessTokenAsync(InputArguments input)
   at Microsoft.AzureRepos.AzureReposHostProvider.GetCredentialAsync(InputArguments input)
   at GitCredentialManager.Commands.GetCommand.ExecuteInternalAsync(InputArguments input, IHostProvider provider)
   at GitCredentialManager.Commands.GitCommandBase.ExecuteAsync()
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by ldennington** [comment]
Can you try setting the following and re-running your clone?

`git config --global credential.azreposCredentialType oauth`

**Comment by TamasSzerb** [comment]
Just works, thank you! Could you please explain why is that?

**Comment by TamasSzerb** [comment]
I see: https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/configuration.md#credentialazreposcredentialtype

**Comment by ldennington** [comment]
Yep 😊. I imagine an expired PAT was the culprit here, but you shouldn't have that issue any longer now that you've updated to OAuth!
