### ISSUE TITLE
HttpClient Timeout when connecting to Bitbucket https

### ISSUE THREAD

**Issue by sursill** [GitCredentialManager/git-credential-manager#555]
**Which version of GCM are you using?**

From a terminal, run `git credential-manager-core --version` and paste the output.

2.0.605+97323d1677

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [x] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [ ] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

When doing anything that needs to connect to our remote repository, it doesn't respond for a few minutes and returns an error regarding HttpClient Timeout(Logs pasted below). Git then just asks for a password.

I tried to reinstall a couple of times, but to no avail. I tried running `git-credential-manager-core-bin diagnose` and it encountered an Exception regarding the HttpClient. Logs are pasted below

Running on Arch Linux, installed AUR `git-credential-manager-core-bin 2.0.605-1` via `yay`
This was running fine, until I did a system-wide update on the weekend.

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

When connecting to remote via `git fetch origin`:
```
fatal: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
fatal: The operation was canceled.
fatal: The operation was canceled.
Password for 'https://example@bitbucket.org':
```

When I ran git-credential-manager-core diagnose:
```
 [ OK ] Environment                                                                                                                                                     
 [ OK ] File system
 [FAIL] Networking

    [!] Encountered an exception [!]
    System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
     ---> System.TimeoutException: The operation was canceled.
     ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
       at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
       at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, Cancellation
Token cancellationToken)
       --- End of inner exception stack trace ---
       --- End of inner exception stack trace ---
       at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, Cancellation
Token cancellationToken)
       at GitCredentialManager.Diagnostics.NetworkingDiagnostic.RunTestAsync(StringBuilder log, HttpClient httpClient)
       at GitCredentialManager.Diagnostics.NetworkingDiagnostic.RunInternalAsync(StringBuilder log, IList`1 additionalFiles)
       at GitCredentialManager.Diagnostics.Diagnostic.RunAsync()

[*] Diagnostic test log [*]
    Checking basic networking and HTTP stack...
    Creating HTTP client... OK
    IsNetworkAvailable: True
    Sending HEAD request to http://example.com...

 [ OK ] Git
  >>>>  Credential storagegit-credential-manager-core: ../libsecret/egg/egg-secure-memory.c:596: sec_free: Assertion `cell->requested > 0' failed.
[1]    13593 abort (core dumped)  git-credential-manager-core diagnose
```

**Comment by mjcheetham** [comment]
Hello @sursill!

Hmm.. from the error and diagnostic traceback, it looks like there's a problem with your network connection somehow.

> Sending HEAD request to http://example.com...
> ...
> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

Please can you try running `wget http://example.com` from your shell and see what behaviour you observe?

Does it succeed, and if so how long did it take? Example output:

```shell
$ wget http://example.com
--2022-01-07 14:58:56--  http://example.com/
Resolving example.com (example.com)... 93.184.216.34, 2606:2800:220:1:248:1893:25c8:1946
Connecting to example.com (example.com)|93.184.216.34|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1256 (1.2K) [text/html]
Saving to: ‘index.html’

index.html        100%[==================================================>]   1.23K  --.-KB/s    in 0s      

2022-01-07 14:58:56 (43.2 MB/s) - ‘index.html’ saved [1256/1256]
```

**Comment by mjcheetham** [comment]
Closing this issue as no response since January. If this is still an issue please open a new ticket, however, it appears the problem is not with GCM but with your network setup (likely caused by the OS update you mentioned).

**Comment by RonaldoSurdi** [comment]
Desculpe tive problemas pessoais
Gostaria muito de sua ajuda para poder contribuir

Em qua., 16 de mar. de 2022 às 19:04, Matthew John Cheetham <
***@***.***> escreveu:
