### ISSUE TITLE
`fatal: The SSL connection could not be established` after successful browser authentication

### ISSUE THREAD

**Issue by corneliusroemer** [GitCredentialManager/git-credential-manager#572]
**Which version of GCM are you using?**

From a terminal, run `git credential-manager-core --version` and paste the output.

Git Credential Manager version 2.0.605+97323d1677 (macOS)

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [x] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [x] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [x] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

When running `git push` I go through the authentication flow, but I get the following error after I authorized gcm on Github:
```
❯ git push
info: please complete authentication in your browser...
fatal: The SSL connection could not be established, see inner exception.
fatal: Unknown format in import.
Username for 'https://github.com': 
```

The webpage I'm on looks like this:
![image](https://user-images.githubusercontent.com/25161793/146113639-9c830bb1-db5b-43ed-8761-f88389920cff.png)
and is on `http://localhost:50254/?code=88xxxxx....`

**Logs**

```
❯ git-credential-manager-core diagnose
Running diagnostics...

 [ OK ] Environment
 [ OK ] File system
 [ OK ] Networking
 [ OK ] Git
 [ OK ] Credential storage
 [ OK ] Microsoft authentication (AAD/MSA)
 [FAIL] GitHub API

    [!] Encountered an exception [!]
    System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
     ---> Interop+AppleCrypto+AppleCommonCryptoCryptographicException: Unknown format in import.
       at Internal.Cryptography.Pal.X509Pal.AppleX509Pal.GetCertContentType(ReadOnlySpan`1 rawData)
       at System.Security.Cryptography.X509Certificates.X509Certificate2.GetCertContentType(ReadOnlySpan`1 rawData)
       at Internal.Cryptography.Pal.StorePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
       at Internal.Cryptography.Pal.StorePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
       at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
       at GitCredentialManager.HttpClientFactory.<>c__DisplayClass5_0.<CreateClient>b__1(X509Certificate2 cert, X509Chain chain, SslPolicyErrors errors)
       at GitCredentialManager.HttpClientFactory.<>c__DisplayClass5_0.<CreateClient>b__2(HttpRequestMessage _, X509Certificate2 cert, X509Chain chain, SslPolicyErrors errors)
       at System.Net.Http.ConnectHelper.<>c__DisplayClass3_0.<EstablishSslConnectionAsync>b__0(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
       at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertificateValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
       at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
       at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
       at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
       --- End of inner exception stack trace ---
       at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
       at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
       at GitHub.GitHubRestApi.GetMetaInfoAsync(Uri targetUri)
       at GitHub.Diagnostics.GitHubApiDiagnostic.RunInternalAsync(StringBuilder log, IList`1 additionalFiles)
       at GitCredentialManager.Diagnostics.Diagnostic.RunAsync()

    [*] Diagnostic test log [*]
    Using 'https://github.com/' as API target.
    Querying '/meta' endpoint...


Diagnostic summary: 6 passed, 0 skipped, 1 failed.
Log files:
  /Users/cr/code/ncov-simplest/gcm-diagnose.log

Caution: Log files may include sensitive information - redact before sharing.

Diagnostics indicate a possible problem with your installation.
Please open an issue at https://aka.ms/gcmcore-bug and include log files.

```

**Comment by ldennington** [comment]
Per #473: GCM is failing because it cannot establish a secure TLS (SSL) connection to the remote, and the problem is an untrusted root certificate. Are you running behind a web proxy or VPN?

I believe the user who opened the previous issue had changed his OpenSSL version - have you changed your OpenSSL version recently? Also, what do you click the HTTPS "padlock" icon at github.com?

**Comment by corneliusroemer** [comment]
You are right, it may have been that I was using a VPN.

It now works after uninstalling and reinstalling.

I configured without VPN, but configuring seems to work with VPN too. Strange. I'll close it since problem is gone.

**Comment by mahdiyarshah** [comment]
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcm/tlsverify for more information.
remote: Repository not found.
fatal: repository 'https://github.com/Stability-AI/stablediffusion.git/' not found
Couldn't launch python

exit code: 9009

stderr:
'"D:\Program Files (x86)\python"' is not recognized as an internal or external command,
operable program or batch file.

Launch unsuccessful. Exiting.
Press any key to continue . . .
