### ISSUE TITLE
Failed to set console mode 0x57 on Windows headless prompts

### ISSUE THREAD

**Issue by mjcheetham** [GitCredentialManager/git-credential-manager#576]
**Which version of GCM are you using?**
2.0.605

**Which Git host provider are you trying to connect to?**

* [x] Other - any provider that supports terminal-based prompts

**Can you access the remote repository directly in the browser using the remote URL?**

Yes.

**Repro steps**

1. Download and install the Microsoft-fork of Git for Windows v2.34.1 (https://github.com/microsoft/git/releases/tag/v2.34.1.vfs.0.0)
2. Connect to the Windows machine from other computer over SSH
3. Attempt to do a Git clone of a private repository

**Expected behavior**

Text-based authentication prompts ask you to select an authentication mode, and enter secret information such as a PAT or password. For example with GitHub and PAT authentication:

```
Select an authentication method for 'https://github.com/':
  1. Web browser (default)
  2. Device code
  3. Personal access token
option (enter for default): 3
Enter GitHub personal access token for 'https://github.com/'...
Token:
```

**Actual behavior**

Typing any character or selecting an authentication mode that masks typed input crashes GCM with the error:

```
Select an authentication method for 'https://github.com/':
  1. Web browser (default)
  2. Device code
  3. Personal access token
option (enter for default): 16:14:31.038697 ...ndowsTerminal.cs:186 trace: [.ctor] Setting console echo state to 'True'
Enter GitHub personal access token for 'https://github.com/'...
Token: 16:14:34.019776 ...ndowsTerminal.cs:186 trace: [.ctor] Setting console echo state to 'False'
fatal: Failed to set console mode [0x57]
   at GitCredentialManager.Interop.Windows.Native.Win32Error.ThrowIfError(Int32 error, String defaultErrorMessage)
   at GitCredentialManager.Interop.Windows.WindowsTerminal.TtyContext..ctor(ITrace trace, SafeFileHandle stream, Boolean echo)
```

**Logs**

Trace logs show that the problem is `Failed to set console mode [0x57]`, "Invalid Parameter".

Investigation shows the problem only occurs when **_Git_** invokes GCM. The call in the `WindowsTerminal` class to `GetConsoleMode` on the `CONIN$` handle returns an unexpected value for the console mode `uint`.

The mode comes back as `520` or `0x208` which is [`ENABLE_VIRTUAL_TERMINAL_INPUT | ENABLE_WINDOW_INPUT `](https://docs.microsoft.com/en-us/windows/console/getconsolemode). We are unable to set the console mode after XOR-ing with `0x4` to clear the `ENABLE_ECHO_INPUT` flag.

We expect the default/"cooked" input handle to `503` or `0x1F7` which is basically the inverse of the above!

This only reproduces when GCM is called from Git.. NOT when GCM is called directly. This indicates a problem with an interaction with the MSYS2 Runtime. Furthermore, only the Microsoft-fork of Git v2.34.1 reproduces this problem!

Looking at the packages used in Git for Windows 2.34.1 and MS-Git 2.34.1, the MSYS2 Runtime has had a large version bump. This points to the likely culprit.

cc @dscho @ldennington

**Comment by dscho** [comment]
I can reproduce this issue, with the following C program:

```c
#include <windows.h>
#include <stdio.h>

int main(int argc, char **argv)
{
	HANDLE handle = CreateFile("CONIN$",
				   GENERIC_READ | GENERIC_WRITE,
				   FILE_SHARE_READ | FILE_SHARE_WRITE,
				   NULL,
				   OPEN_EXISTING,
				   FILE_ATTRIBUTE_NORMAL,
				   NULL);
	DWORD mode;
	BOOL result = GetConsoleMode(handle, &mode);

	if (!result)
		fprintf(stderr, "Could not get console mode\n");
	else {
		fprintf(stderr, "Got mode 0x%x\n", mode);
		if (argc > 1) {
			result = SetConsoleMode(handle, mode ^ ENABLE_ECHO_INPUT);
			fprintf(stderr, "result setting mode: %d\n", result);
		}
	}

	CloseHandle(handle);

	return result ? 0 : 1;
}
```

All I need to do is to run this through `git -c "alias.x=!program.exe </dev/null" x` in a `cmd`. It reproduces the issue as soon as we're using MSYS2 runtime v3.3.3.

**Comment by mjcheetham** [comment]
Thanks @dscho! This is the smoking gun that MSYS2 runtime v3.3.3 has a breaking change in the console handling.

We should be getting (and used to get in versions prior to 3.3.3) a console mode of `0x1F7` from `CONIN$`, _not_ `0x208`.

**Comment by dscho** [comment]
I am actually getting `0x7` when running the reproducer with MSYS2 runtime v3.1.7-6 (which was the version Git for Windows used before upgrading to v3.3.3, we skipped v3.2.x precisely because of those console-related breakages).

**Comment by dscho** [comment]
FWIW I was able to verify that this very same issue happens also in Cygwin.

**Comment by mjcheetham** [comment]
Git for Windows patch that corrects this problem in Cygwin/MSYS2:

https://github.com/git-for-windows/msys2-runtime/pull/38

**Comment by mjcheetham** [comment]
This is not a bug in GCM, but in the specific version of the MSYS2 runtime that shipped with microsoft/git 2.34.1. No further action required for GCM.

**Comment by dscho** [comment]
I tested Git for Windows' latest [snapshot](https://wingit.blob.core.windows.net/files/index.html) and verified that it fixes the bug.
