### ISSUE TITLE
Rate Limit Cant Authenticated

### ISSUE THREAD

**Issue by fuatakbar** [GitCredentialManager/git-credential-manager#645]
$ git credential-manager-core diagnose
Running diagnostics...

 [ OK ] Environment
 [ OK ] File system
  >>>>  Networking
[ OK ] Networking
 [ OK ] Git
 [ OK ] Credential storage
 [ OK ] Microsoft authentication (AAD/MSA)
 [FAIL] GitHub API

    [!] Encountered an exception [!]
    System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (rate limit exceeded).

       at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()

       at GitHub.GitHubRestApi.<GetMetaInfoAsync>d__5.MoveNext()

    --- End of stack trace from previous location where exception was thrown ---

       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

       at GitHub.Diagnostics.GitHubApiDiagnostic.<RunInternalAsync>d__2.MoveNext()

    --- End of stack trace from previous location where exception was thrown ---

       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

       at GitCredentialManager.Diagnostics.Diagnostic.<RunAsync>d__5.MoveNext()

    [*] Diagnostic test log [*]
    Using 'https://github.com/' as API target.

    Querying '/meta' endpoint...

Diagnostic summary: 6 passed, 0 skipped, 1 failed.
Log files:
  D:\Project\open-rp\gcm-diagnose.log

Caution: Log files may include sensitive information - redact before sharing.

Diagnostics indicate a possible problem with your installation.
Please open an issue at https://aka.ms/gcm/bug and include log files.

**Comment by mjcheetham** [comment]
The error you're getting (`403 (rate limit exceeded)`) seems to indicate that your IP address has been making many calls to the GitHub API recently. Have you been making lots of requests recently? Either way trying again after a period of time should "fix" the problem - you will no longer be throttled.
