### ISSUE TITLE
Unable to store credential with DPAPI when connected via ssh key-based auth

### ISSUE THREAD

**Issue by Vynce** [GitCredentialManager/git-credential-manager#666]
**Which version of GCM are you using?**

GCM v2.0.696+4365b917da (on Windows 10 20H2)

---

**Environment**

I'm trying to seed credentials to Jenkins agents running in internal cloud infrastructure. The connection to each agent is via **ssh key-based authentication**. Each agent runs as a unique local user (so pre-generating a DPAPI-encrypted credential file and copying it to each agent won't work).

**Expected behavior**

The provided credential is encrypted and successfully stored using the DPAPI backend.

**Actual behavior**

The store operation fails with an Access Denied error.

Configurations that **do** work:
* Connection to the agent is via **ssh password-based authentication**.
* Connection to the agent is via ssh key-based authentication AND the same user is concurrently logged in via password-based authentication.
* Plaintext credential store backend.

This is probably the same issue as #325, but it sounded like the hope was that DPAPI would work around all the network auth issues that affect wincredman (?).

**Logs**

```bash
export GCM_INTERACTIVE=0
export GCM_CREDENTIAL_STORE=dpapi
export GCM_DPAPI_STORE_PATH=.
export GIT_TRACE=1
export GCM_TRACE=1

echo -e "protocol=https\nhost=hostname\nusername=user\npassword=pass" | git credential-manager-core store
```
```
20:06:28.564448 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
20:06:28.565975 git.c:746               trace: exec: git-credential-manager-core store
20:06:28.565975 run-command.c:654       trace: run_command: git-credential-manager-core store
20:06:28.716671 ...\Application.cs:95   trace: [RunInternalAsync] Version: 2.0.696.25923
20:06:28.721217 ...\Application.cs:96   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
20:06:28.721217 ...\Application.cs:97   trace: [RunInternalAsync] Platform: Windows (x86-64)
20:06:28.721217 ...\Application.cs:98   trace: [RunInternalAsync] OSVersion: 10.0 (build 19042)
20:06:28.721217 ...\Application.cs:99   trace: [RunInternalAsync] AppPath: C:\Program Files\Git\mingw64\libexec\git-core\git-credential-manager-core.exe
20:06:28.721217 ...\Application.cs:100  trace: [RunInternalAsync] Arguments: store
20:06:28.797575 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'store' command...
20:06:28.826855 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
20:06:28.828886 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	protocol=https
20:06:28.828886 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	host=hostname
20:06:28.828886 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	username=user
20:06:28.828886 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	password=********
20:06:28.999508 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
20:06:29.029877 ...viderRegistry.cs:158 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
20:06:29.032898 ...viderRegistry.cs:166 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
20:06:29.036951 ...viderRegistry.cs:181 trace: [GetProviderAsync] Querying remote URL for host provider auto-detection.
20:06:29.039975 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
warning: auto-detection of host provider took too long (>2000ms)
warning: see https://aka.ms/gcm/autodetect for more information.
20:06:31.838442 ...viderRegistry.cs:166 trace: [GetProviderAsync] Checking against 1 host providers registered with priority 'Low'.
20:06:31.838442 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'Generic' was selected.
20:06:31.839479 ...\HostProvider.cs:160 trace: [StoreCredentialAsync] Storing credential with service=https://hostname/ account=user...
fatal: Access is denied.

   at System.Security.Cryptography.ProtectedData.Protect(Byte[] userData, Byte[] optionalEntropy, DataProtectionScope scope)
   at GitCredentialManager.Interop.Windows.DpapiCredentialStore.SerializeCredential(FileCredential credential)
   at GitCredentialManager.PlaintextCredentialStore.AddOrUpdate(String service, String account, String secret)
   at GitCredentialManager.CredentialStore.AddOrUpdate(String service, String account, String secret)
   at GitCredentialManager.HostProvider.StoreCredentialAsync(InputArguments input)
   at GitCredentialManager.Commands.StoreCommand.ExecuteInternalAsync(InputArguments input, IHostProvider provider)
   at GitCredentialManager.Commands.GitCommandBase.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.CommandHandler.<GetExitCodeAsync>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.<InvokeAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by ldennington** [comment]
Thank you for raising this issue. We do not recommend the use of GCM in headless environment due to this type of explosion in complexity. Potentially consider looking at the Jenkins documentation to see what is recommended for this scenario or raising an issue with the Jenkins project.
