### ISSUE TITLE
Latest standalone GCM installation fails on Windows due to hard dependency on git.exe

### ISSUE THREAD

**Issue by ashemedai** [GitCredentialManager/git-credential-manager#770]
Trying to install (or uninstall) `gcmcore-win-x86-2.0.696.exe` on Windows 10 (21H1) fails. You get this popup and wonder what is going wrong:

![image](https://user-images.githubusercontent.com/610865/176652200-63ec2c55-b45b-4969-a712-6029755b98d4.png)

All the files do get installed correctly into `C:\Program Files (x86)\Git Credential Manager`. Running `git-credential-manager-core.exe` from that directory gives the following:

![image](https://user-images.githubusercontent.com/610865/176652889-f367ae77-1726-41d8-ae89-0a2626396279.png)

This flies against what is documented at https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/wsl.md#configuring-wsl-without-git-for-windows since it seems to want to be able to find a `git.exe`. So somewhere some hardcoded dependency on git.exe has been added.

**Comment by ashemedai** [comment]
@ldennington That link was already in my original message. For completeness sake, let me quote from https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/wsl.md#configuring-wsl-without-git-for-windows:

> If you wish to use GCM inside of WSL without installing Git for Windows you must complete additional configuration so that GCM can callback to Git inside of your WSL installation.

The particular use case is transparent use of credentials from the Windows Credential Manager to git in WSL. This is a much friendlier user experience for people not versed in Linux, but who need to use WSL for projects via their Windows VS Code installation. (All credits to @mjcheetham for documenting this in the first place.)

So there *is* a git installation, it just happens to reside within WSL and is made accessible via WSL's `GIT_EXEC_PATH/wp`.

**Comment by ldennington** [comment]
Just to confirm - the specific problem here is that the installer fails when you don't have a git executable on your Windows PATH because it lives inside WSL? @mjcheetham - heads up on this...is there a way to avoid calling `git-credential-manager-core configure` from the Inno Setup script in this scenario?

**Comment by Mrkojtis** [comment]
Ok! 👍 And then can the token be a crypted individual id number special
signs! We make ur own special signs tangentbord! With only us for
administrating the fysical use of this special numbers!

Ask if you wondering something about the way I thinking!

You are the best! ❤️ All of you!!



Den tors 21 juli 2022 15:01Jeroen Ruigrok van der Werven <
***@***.***> skrev:

**Comment by ivailop** [comment]
I encountered one more use case, independent of the GCM standalone installation.
If you install the [Git for Windows](https://github.com/git-for-windows/git/releases/tag/v2.39.0.windows.2) and **do not update the Windows system PATH** (as you don't want to pollute the system) any use of GCM (from Windows terminal or WSL) would fail with:
```
Unhandled Exception: System.Exception: Failed to locate 'git.exe' executable on the path.
   at GitCredentialManager.EnvironmentExtensions.LocateExecutable(IEnvironment environment, String program)
   at GitCredentialManager.CommandContext.GetGitPath(IEnvironment environment, IFileSystem fileSystem, ITrace trace)
   at GitCredentialManager.CommandContext..ctor(String appPath, String installDir)
   at GitCredentialManager.Program.Main(String[] args)
```

Based on the implementation, [`git.exe` is expected to be on the PATH](https://github.com/GitCredentialManager/git-credential-manager/blob/df9a165895cf4be121c599d23c1da83d57ea90b0/src/shared/Core/EnvironmentBase.cs#L112-L139)

However on Windows, search of executable is the done different compared to Linux - the **current directory** is checked before the `PATH`.

In fact, "Git for Windows" places both `git-credential-manager-core.exe` and `git.exe` in the same directory
![image](https://user-images.githubusercontent.com/5092875/211406392-b63a89b1-64e8-4fe4-9caf-8d5b5d065d34.png)

**Comment by ldennington** [comment]
@ivailop - are you using Windows or WSL? I'm not sure this can be considered a separate use case for the same issue if the former.

**Comment by ivailop** [comment]
> @ivailop - are you using Windows or WSL? I'm not sure this can be considered a separate use case for the same issue if the former.

I encountered the problem using WSL. While figuring out the issue, tried simply running:
* in WSL console
```
/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager.exe --version
```
* and Windows cmd
```
"C:\Program Files\Git\mingw64\bin\git-credential-manager.exe" --version
```
And in both cases got the same error (as mentioned above)

**Comment by mjcheetham** [comment]
Closing stale issue. GCM in WSL requires Git for Windows to be installed, even if you are only using Git inside of WSL. Important GCM configuration is stored in Git config, and this means it must be available where GCM is running (the Windows host).
