### ISSUE TITLE
GCM w/gpg/pass push errors with PAT or browser authentication.

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [GitCredentialManager/git-credential-manager#811]
**Which version of GCM are you using?**

2.0.785+6074e4e3d3

**Which Git host provider are you trying to connect to?**

* [X] GitHub

**Can you access the remote repository directly in the browser using the remote URL?**

* [X] Yes

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [X] Not applicable
* 
**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [X] Not applicable
---

**Expected behavior**
`git push` works without errors either using browser authentication or PAT

**Actual behavior**
Push succeeds, but gives the error:
```
info: please complete authentication in your browser...
fatal: Failed to encrypt file '/home/xenophon/.password-store/git/https/github.com/Jacob-Stevens-Haas.gpg' with gpg. exit=2, out=, err=gpg: error retrieving '37048747+Jacob-Stevens-Haas@users.noreply.github.com' via WKD: General error
gpg: 37048747+Jacob-Stevens-Haas@users.noreply.github.com: skipped: General error
gpg: [stdin]: encryption failed: General error

Everything up-to-date
```

Previously, I had had my gpg key associated with my personal email account.  I had been getting errors with signing commits, and realized I needed to git config `user.email` to my personal account and not `Jacob-Stevens-Haas@users.noreply.github.com`.  I did so, and signing commits worked.  However, when i noticed the line `fatal: Failed to encrypt file:...error retrieving '37048747+Jacob-Stevens-Haas@users.noreply.github.com' via WKD: General Error`, I added the noreply email as a gpg key user.

**Logs**

<details>

<summary> `git push`, selecting browser authentication </summary>

```
16:56:23.555141 git.c:439               trace: built-in: git push
16:56:23.555743 run-command.c:663       trace: run_command: GIT_DIR=.git git-remote-https origin https://github.com/Jacob-Stevens-Haas/gen-experiments
16:56:23.780886 run-command.c:663       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager-core get'
16:56:23.941522 ...re/Application.cs:95 trace: [RunInternalAsync] Version: 2.0.785.29792
16:56:23.942747 ...re/Application.cs:96 trace: [RunInternalAsync] Runtime: .NET 6.0.3
16:56:23.942780 ...re/Application.cs:97 trace: [RunInternalAsync] Platform: Linux (x86-64)
16:56:23.942788 ...re/Application.cs:98 trace: [RunInternalAsync] OSVersion: Linux pontus 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
16:56:23.942839 ...re/Application.cs:99 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager-core
16:56:23.942862 ...e/Application.cs:100 trace: [RunInternalAsync] Arguments: get
16:56:24.013250 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'get' command...
16:56:24.022565 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
16:56:24.023908 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	protocol=https
16:56:24.023945 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	host=github.com
16:56:24.049989 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
16:56:24.052563 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
16:56:24.054101 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
16:56:24.055045 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
16:56:24.057026 .../HostProvider.cs:126 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://github.com account=...
16:56:24.064282 ...edentialStore.cs:352 trace: [GetGpgPath] Using PATH-located GPG (gpg) executable: /usr/bin/gpg
16:56:24.068843 .../HostProvider.cs:131 trace: [GetCredentialAsync] No existing credentials found.
16:56:24.068870 .../HostProvider.cs:134 trace: [GetCredentialAsync] Creating new credential...
16:56:24.074533 ...bHostProvider.cs:255 trace: [GetSupportedAuthenticationModesAsync] https://github.com/ is github.com - authentication schemes: 'Pat, OAuth'
16:56:24.089159 ...enticationBase.cs:40 trace: [InvokeHelperAsync] Starting helper process: /usr/local/share/gcm-core/GitHub.UI prompt --browser --device --pat
16:56:30.885221 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
info: please complete authentication in your browser...
16:56:32.289931 .../GitHubRestApi.cs:95 trace: [GetUserInfoAsync] HTTP: GET https://api.github.com/user
16:56:32.290207 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
16:56:32.566912 ...GitHubRestApi.cs:102 trace: [GetUserInfoAsync] HTTP: Response 200 [OK]
16:56:32.606490 .../HostProvider.cs:136 trace: [GetCredentialAsync] Credential created.
16:56:32.608602 ...GitCommandBase.cs:54 trace: [ExecuteAsync] End 'get' command...
16:56:32.985709 run-command.c:663       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager-core store'
16:56:33.125589 ...re/Application.cs:95 trace: [RunInternalAsync] Version: 2.0.785.29792
16:56:33.127016 ...re/Application.cs:96 trace: [RunInternalAsync] Runtime: .NET 6.0.3
16:56:33.127048 ...re/Application.cs:97 trace: [RunInternalAsync] Platform: Linux (x86-64)
16:56:33.127064 ...re/Application.cs:98 trace: [RunInternalAsync] OSVersion: Linux pontus 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
16:56:33.127126 ...re/Application.cs:99 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager-core
16:56:33.127156 ...e/Application.cs:100 trace: [RunInternalAsync] Arguments: store
16:56:33.219771 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'store' command...
16:56:33.238487 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
16:56:33.239890 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	protocol=https
16:56:33.239924 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	host=github.com
16:56:33.239933 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	username=Jacob-Stevens-Haas
16:56:33.239942 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	password=********
16:56:33.268735 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
16:56:33.271982 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
16:56:33.273711 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
16:56:33.274928 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
16:56:33.275676 .../HostProvider.cs:160 trace: [StoreCredentialAsync] Storing credential with service=https://github.com account=Jacob-Stevens-Haas...
16:56:33.284146 ...edentialStore.cs:352 trace: [GetGpgPath] Using PATH-located GPG (gpg) executable: /usr/bin/gpg
fatal: Failed to encrypt file '/home/xenophon/.password-store/git/https/github.com/Jacob-Stevens-Haas.gpg' with gpg. exit=2, out=, err=gpg: error retrieving '37048747+Jacob-Stevens-Haas@users.noreply.github.com' via WKD: General error
gpg: 37048747+Jacob-Stevens-Haas@users.noreply.github.com: skipped: General error
gpg: [stdin]: encryption failed: General error

   at GitCredentialManager.Gpg.EncryptFile(String path, String gpgId, String contents)
   at GitCredentialManager.Interop.Posix.GpgPassCredentialStore.SerializeCredential(FileCredential credential)
   at GitCredentialManager.PlaintextCredentialStore.AddOrUpdate(String service, String account, String secret)
   at GitCredentialManager.CredentialStore.AddOrUpdate(String service, String account, String secret)
   at GitCredentialManager.HostProvider.StoreCredentialAsync(InputArguments input)
   at GitCredentialManager.Commands.StoreCommand.ExecuteInternalAsync(InputArguments input, IHostProvider provider)
   at GitCredentialManager.Commands.GitCommandBase.ExecuteAsync()
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```
</details>

Brings up web page with the note 
```
Authentication Succeeded

You may now close this tab and return to the application.
```

<details>

<summary> `git push` using token </summary>

```
16:57:40.212511 git.c:439               trace: built-in: git push
16:57:40.213435 run-command.c:663       trace: run_command: GIT_DIR=.git git-remote-https origin https://github.com/Jacob-Stevens-Haas/gen-experiments
16:57:40.435562 run-command.c:663       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager-core get'
16:57:40.592521 ...re/Application.cs:95 trace: [RunInternalAsync] Version: 2.0.785.29792
16:57:40.593697 ...re/Application.cs:96 trace: [RunInternalAsync] Runtime: .NET 6.0.3
16:57:40.593729 ...re/Application.cs:97 trace: [RunInternalAsync] Platform: Linux (x86-64)
16:57:40.593743 ...re/Application.cs:98 trace: [RunInternalAsync] OSVersion: Linux pontus 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
16:57:40.593795 ...re/Application.cs:99 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager-core
16:57:40.593817 ...e/Application.cs:100 trace: [RunInternalAsync] Arguments: get
16:57:40.673007 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'get' command...
16:57:40.681955 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
16:57:40.683119 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	protocol=https
16:57:40.683145 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	host=github.com
16:57:40.708696 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
16:57:40.711316 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
16:57:40.712816 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
16:57:40.714033 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
16:57:40.715925 .../HostProvider.cs:126 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://github.com account=...
16:57:40.723111 ...edentialStore.cs:352 trace: [GetGpgPath] Using PATH-located GPG (gpg) executable: /usr/bin/gpg
16:57:40.727640 .../HostProvider.cs:131 trace: [GetCredentialAsync] No existing credentials found.
16:57:40.727670 .../HostProvider.cs:134 trace: [GetCredentialAsync] Creating new credential...
16:57:40.733232 ...bHostProvider.cs:255 trace: [GetSupportedAuthenticationModesAsync] https://github.com/ is github.com - authentication schemes: 'Pat, OAuth'
16:57:40.747836 ...enticationBase.cs:40 trace: [InvokeHelperAsync] Starting helper process: /usr/local/share/gcm-core/GitHub.UI prompt --browser --device --pat
16:57:53.966941 .../GitHubRestApi.cs:95 trace: [GetUserInfoAsync] HTTP: GET https://api.github.com/user
16:57:53.974246 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
16:57:54.504004 ...GitHubRestApi.cs:102 trace: [GetUserInfoAsync] HTTP: Response 200 [OK]
16:57:54.621036 .../HostProvider.cs:136 trace: [GetCredentialAsync] Credential created.
16:57:54.621987 ...GitCommandBase.cs:54 trace: [ExecuteAsync] End 'get' command...
16:57:54.782748 run-command.c:663       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager-core store'
16:57:54.939948 ...re/Application.cs:95 trace: [RunInternalAsync] Version: 2.0.785.29792
16:57:54.941150 ...re/Application.cs:96 trace: [RunInternalAsync] Runtime: .NET 6.0.3
16:57:54.941180 ...re/Application.cs:97 trace: [RunInternalAsync] Platform: Linux (x86-64)
16:57:54.941197 ...re/Application.cs:98 trace: [RunInternalAsync] OSVersion: Linux pontus 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
16:57:54.941250 ...re/Application.cs:99 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager-core
16:57:54.941274 ...e/Application.cs:100 trace: [RunInternalAsync] Arguments: store
16:57:55.010385 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'store' command...
16:57:55.024965 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
16:57:55.028642 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	protocol=https
16:57:55.028679 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	host=github.com
16:57:55.028688 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	username=Jacob-Stevens-Haas
16:57:55.028698 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	password=********
16:57:55.059942 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
16:57:55.063006 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
16:57:55.064776 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
16:57:55.065959 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
16:57:55.066790 .../HostProvider.cs:160 trace: [StoreCredentialAsync] Storing credential with service=https://github.com account=Jacob-Stevens-Haas...
16:57:55.076081 ...edentialStore.cs:352 trace: [GetGpgPath] Using PATH-located GPG (gpg) executable: /usr/bin/gpg
fatal: Failed to encrypt file '/home/xenophon/.password-store/git/https/github.com/Jacob-Stevens-Haas.gpg' with gpg. exit=2, out=, err=gpg: error retrieving '37048747+Jacob-Stevens-Haas@users.noreply.github.com' via WKD: General error
gpg: 37048747+Jacob-Stevens-Haas@users.noreply.github.com: skipped: General error
gpg: [stdin]: encryption failed: General error

   at GitCredentialManager.Gpg.EncryptFile(String path, String gpgId, String contents)
   at GitCredentialManager.Interop.Posix.GpgPassCredentialStore.SerializeCredential(FileCredential credential)
   at GitCredentialManager.PlaintextCredentialStore.AddOrUpdate(String service, String account, String secret)
   at GitCredentialManager.CredentialStore.AddOrUpdate(String service, String account, String secret)
   at GitCredentialManager.HostProvider.StoreCredentialAsync(InputArguments input)
   at GitCredentialManager.Commands.StoreCommand.ExecuteInternalAsync(InputArguments input, IHostProvider provider)
   at GitCredentialManager.Commands.GitCommandBase.ExecuteAsync()
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
Everything up-to-date
```
</details>
Token gives same error and doesn't save.  Successive pushes require re-adding PAT.

<details>

<summary> relevant `git config --global --list` (none are overwritten in `--local` or `--user`) </summary>

```
credential.credentialstore=gpg
credential.helper=/usr/local/share/gcm-core/git-credential-manager-core
user.email=<personal email>
user.name=Jacob Stevens-Haas
core.editor=nano
commit.gpgsign=true
credential.https://dev.azure.com.usehttppath=true
```
</details>

**Comment by ldennington** [comment]
Do you still have your personal account set up as a gpg key user (in addition to the noreply email)?

**Comment by Jacob-Stevens-Haas** [comment]
yes, I do, and both are listed as `[ultimate]` trust.

**Comment by mjcheetham** [comment]
Hi @Jacob-Stevens-Haas, could you please tell me the contents of the following file (if it exists)? It should be the email/ID of the associated GPG key used to encrypt your credentials locally on disk.

```
/home/xenophon/.password-store/.gpg-id
```

Do you also have the `pass` program installed? What happens if you try and use `pass` to read/write a simple test credential?

```console
% pass insert test-cred
Enter password for test-cred: 
Retype password for test-cred: 
[main 75cd33d] Add given password for test-cred to store.
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test-cred.gpg
% pass show test-cred
mysecretpassword
```

**Comment by Jacob-Stevens-Haas** [comment]
@mjcheetham, here's the result:
```
user@domain:~$ cat /home/xenophon/.password-store/.gpg-id
37048747+Jacob-Stevens-Haas@users.noreply.github.com
```

I do have `pass` installed, here's the result of inserting `test-cred`
```
user@domain:~$ pass insert test-cred
Enter password for test-cred: 
Retype password for test-cred: 
gpg: error retrieving '37048747+Jacob-Stevens-Haas@users.noreply.github.com' via WKD: General error
gpg: 37048747+Jacob-Stevens-Haas@users.noreply.github.com: skipped: General error
gpg: [stdin]: encryption failed: General error
Password encryption aborted.
user@domain:~$ pass show test-cred
Error: test-cred is not in the password store.
```

**Comment by Jacob-Stevens-Haas** [comment]
Thanks for the help!  Looks like it was an issue with `pass`, and deletion/re-adding the gpg id to pass now works :)
