### ISSUE TITLE
fatal: helper error (255): Default font family name can't be null or empty.

### ISSUE THREAD

**Issue by Joonsey** [GitCredentialManager/git-credential-manager#899]
GCM version 2.0.785+6074e4e3d3

only tried on github

**Expected behavior**

I am able to push code to remote repo

**Actual behavior**

I get an exception 
fatal: helper error (255): Default font family name can't be null or empty.

**Logs**
22:21:48.842023 git.c:460               trace: built-in: git push
22:21:48.842118 run-command.c:655       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/Joonsey/didactic-lamp
22:21:48.843101 git.c:750               trace: exec: git-remote-https origin https://github.com/Joonsey/didactic-lamp
22:21:48.843138 run-command.c:655       trace: run_command: git-remote-https origin https://github.com/Joonsey/didactic-lamp
22:21:49.084416 run-command.c:655       trace: run_command: '/usr/share/git-credential-manager-core/git-credential-manager-core get'
22:21:49.183574 ...re/Application.cs:95 trace: [RunInternalAsync] Version: 2.0.785.29792
22:21:49.184411 ...re/Application.cs:96 trace: [RunInternalAsync] Runtime: .NET 6.0.3
22:21:49.184428 ...re/Application.cs:97 trace: [RunInternalAsync] Platform: Linux (x86-64)
22:21:49.184433 ...re/Application.cs:98 trace: [RunInternalAsync] OSVersion: Linux arch 5.19.13-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 04 Oct 2022 14:36:58 +0000 x86_64 GNU/Linux
22:21:49.184470 ...re/Application.cs:99 trace: [RunInternalAsync] AppPath: /usr/share/git-credential-manager-core/git-credential-manager-core
22:21:49.184485 ...e/Application.cs:100 trace: [RunInternalAsync] Arguments: get
22:21:49.260049 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'get' command...
22:21:49.266578 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
22:21:49.267433 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	protocol=https
22:21:49.267444 ...GitCommandBase.cs:48 trace: [ExecuteAsync] 	host=github.com
22:21:49.287068 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
22:21:49.288530 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
22:21:49.289638 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
22:21:49.290409 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
22:21:49.291815 .../HostProvider.cs:126 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://github.com account=...
22:21:49.298083 git.c:460               trace: built-in: git credential-cache get
22:21:49.305361 .../HostProvider.cs:131 trace: [GetCredentialAsync] No existing credentials found.
22:21:49.305380 .../HostProvider.cs:134 trace: [GetCredentialAsync] Creating new credential...
22:21:49.308585 ...bHostProvider.cs:255 trace: [GetSupportedAuthenticationModesAsync] https://github.com/ is github.com - authentication schemes: 'Pat, OAuth'
22:21:49.318265 ...enticationBase.cs:40 trace: [InvokeHelperAsync] Starting helper process: /usr/share/git-credential-manager-core/GitHub.UI prompt --browser --device --pat
fatal: helper error (255): Default font family name can't be null or empty.
   at GitCredentialManager.Authentication.AuthenticationBase.InvokeHelperAsync(String path, String args, IDictionary`2 standardInput, CancellationToken ct)
   at GitHub.GitHubAuthentication.GetAuthenticationAsync(Uri targetUri, String userName, AuthenticationModes modes)
   at GitHub.GitHubHostProvider.GenerateCredentialAsync(InputArguments input)
   at GitCredentialManager.HostProvider.GetCredentialAsync(InputArguments input)
   at GitCredentialManager.Commands.GetCommand.ExecuteInternalAsync(InputArguments input, IHostProvider provider)
   at GitCredentialManager.Commands.GitCommandBase.ExecuteAsync()
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by mjcheetham** [comment]
Hello! This look like a problem with the underlying UI framework we're using.

```
sudo apt-get install ttf-mscorefonts-installer
```

https://github.com/GitCredentialManager/git-credential-manager/issues/775#issuecomment-1232809667

Could you try that command to see if it fixes your problem?

**Comment by Joonsey** [comment]
https://aur.archlinux.org/packages/ttf-ms-fonts

used this package on the AUR and it worked. 
Thanks!
