### ISSUE TITLE
fatal: helper error (139) when clicking "sign in with browser" on the pop-up windows

### ISSUE THREAD

**Issue by willbe03** [GitCredentialManager/git-credential-manager#911]
**Which version of GCM are you using?**

From a terminal, run `git credential-manager-core --version` and paste the output.
2.0.779+57cd9d4e50

**Which Git host provider are you trying to connect to?**

Github

**Can you access the remote repository directly in the browser using the remote URL?**
Yes

From a terminal, run `git remote -v` to see your remote URL.

* [ ] Yes
* [ ] No, I get a permission error
* [x] No, for a different reason - please describe
Git repo not initialized yet.
---

**_[Azure DevOps only]_ What format is your remote URL?**

* [x] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as
you authenticate, check that you selected the same one that has access on the
web.**

* [x] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**
Using WSL2 Ubuntu
Other GUI program such as `gedit` runs normally.
When I clicked "sign in with browser" in the pop-up window, the window disappeared and `fatal: helper error (139)` was displayed. The manager fallback to the normal username-password authentication. I've tried to use GPG instead of `secretservice`, and correctly configured `pass`, but the credential manager was still using a popup GUI, which appeared to be `secretservice`. 

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your
Git command. Review and redact any private information and attach the log.

If you are running inside of Windows Subsystem for Linux (WSL), you must also
set an additional environment variable to enable tracing: `WSLENV=$WSLENV:GCM_TRACE`.
For example:

```shell
WSLENV=$WSLENV:GCM_TRACE:GIT_TRACE GCM_TRACE=1 GIT_TRACE=1 git fetch
```
```
00:24:11.269851 git.c:460               trace: built-in: git clone https://github.com/**/f**.git
Cloning into '**'...
00:24:11.271518 run-command.c:655       trace: run_command: git remote-https origin https://github.com/**/**.git
00:24:11.272260 git.c:750               trace: exec: git-remote-https origin https://github.com/**/**
00:24:11.272298 run-command.c:655       trace: run_command: git-remote-https origin https://github.com**/**
00:24:11.407193 run-command.c:655       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager-core get'
00:24:11.518767 ...re/Application.cs:95 trace: [RunInternalAsync] Version: 2.0.779.52567
00:24:11.520002 ...re/Application.cs:96 trace: [RunInternalAsync] Runtime: .NET 6.0.3
00:24:11.520028 ...re/Application.cs:97 trace: [RunInternalAsync] Platform: Linux (x86-64)
00:24:11.520163 ...re/Application.cs:98 trace: [RunInternalAsync] OSVersion: Linux **-pc 5.15.68.1-microsoft-standard-WSL2 #1 SMP Mon Sep 19 19:14:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
00:24:11.520224 ...re/Application.cs:99 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager-core
00:24:11.520250 ...e/Application.cs:100 trace: [RunInternalAsync] Arguments: get
00:24:11.607625 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'get' command...
00:24:11.612055 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
00:24:11.612774 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   protocol=https
00:24:11.612807 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   host=github.com
00:24:11.626203 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
00:24:11.627526 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
00:24:11.628527 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
00:24:11.629279 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
00:24:11.630225 .../HostProvider.cs:126 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://github.com account=...
00:24:11.647793 .../HostProvider.cs:131 trace: [GetCredentialAsync] No existing credentials found.
00:24:11.647853 .../HostProvider.cs:134 trace: [GetCredentialAsync] Creating new credential...
00:24:11.650590 ...bHostProvider.cs:255 trace: [GetSupportedAuthenticationModesAsync] https://github.com/ is github.com - authentication schemes: 'Pat, OAuth'
00:24:11.658054 ...enticationBase.cs:40 trace: [InvokeHelperAsync] Starting helper process: /usr/local/share/gcm-core/GitHub.UI prompt --browser --device --pat
fatal: helper error (139): Unknown
   at GitCredentialManager.Authentication.AuthenticationBase.InvokeHelperAsync(String path, String args, IDictionary`2 standardInput, CancellationToken ct)
   at GitHub.GitHubAuthentication.GetAuthenticationAsync(Uri targetUri, String userName, AuthenticationModes modes)
   at GitHub.GitHubHostProvider.GenerateCredentialAsync(InputArguments input)
   at GitCredentialManager.HostProvider.GetCredentialAsync(InputArguments input)
   at GitCredentialManager.Commands.GetCommand.ExecuteInternalAsync(InputArguments input, IHostProvider provider)
   at GitCredentialManager.Commands.GitCommandBase.ExecuteAsync()
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
Username for 'https://github.com':
```

**Comment by dscho** [comment]
The exit code is 128 + 11, which suggests a segmentation fault (11 is the numeric value of the signal `SIGSEGV`). Maybe running the entire command through [`strace -ff -o /tmp/gcm.strace`](https://www.man7.org/linux/man-pages/man1/strace.1.html) sheds light into the conundrum?

**Comment by willbe03** [comment]
> The exit code is 128 + 11, which suggests a segmentation fault (11 is the numeric value of the signal `SIGSEGV`). Maybe running the entire command through [`strace -ff -o /tmp/gcm.strace`](https://www.man7.org/linux/man-pages/man1/strace.1.html) sheds light into the conundrum?

I've run `strace`, and there are a lot of files generated in /tmp/gcm.strace.*, ranging from 473 to 545. Should I share all of them, or just the last file generated?
```
$ cat /tmp/gcm.strace.545
set_robust_list(0x7fbe6effd9e0, 24)     = 0
sched_getaffinity(478, 128, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]) = 32
sched_setaffinity(0, 128, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]) = 0
sigaltstack(NULL, {ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}) = 0
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fbebc588000
mprotect(0x7fbebc588000, 4096, PROT_NONE) = 0
sigaltstack({ss_sp=0x7fbebc588000, ss_flags=0, ss_size=16384}, NULL) = 0
gettid()                                = 545
pipe2([87, 88], O_CLOEXEC)              = 0
futex(0x7fbe840062f0, FUTEX_WAKE_PRIVATE, 1) = 1
read(87, "*", 1)                        = 1
futex(0x7fbe84006650, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fbe84006650, FUTEX_WAKE_PRIVATE, 1) = 0
close(87)                               = 0
close(88)                               = 0
mmap(0x7fbe64000000, 67108864, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x7fbe64000000
mprotect(0x7fbe64000000, 135168, PROT_READ|PROT_WRITE) = 0
sched_getaffinity(545, 32, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]) = 32
sched_getaffinity(545, 32, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]) = 32
futex(0x7fbe840063a0, FUTEX_WAIT_PRIVATE, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fbe84006350, FUTEX_WAIT_PRIVATE, 2, NULL) = 0
futex(0x7fbe84006350, FUTEX_WAKE_PRIVATE, 1) = 0
getpid()                                = 478
prctl(PR_SET_NAME, ".NET ThreadPool"...) = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
futex(0x7fbe840063a4, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=307, tv_nsec=181841345}, FUTEX_BITSET_MATCH_ANY) = ?
+++ exited with 255 +++
```

**Comment by dscho** [comment]
@willbe03 it would be more helpful if you analyzed them first, looking for something saying "segmentation fault" or similar.

**Comment by mjcheetham** [comment]
@willbe03 please could you try running the following command and include any output you see on the terminal?

```sh
GCM_TRACE=1 /usr/local/share/gcm-core/GitHub.UI prompt --browser --device --pat
```

If the command is successful you should see a GitHub log in prompt.

**Comment by ldennington** [comment]
@willbe03 - Have you had a chance to run the command @mjcheetham suggested?

**Comment by ldennington** [comment]
Closing due to lack of response.

**Comment by EimalShirzai** [comment]
در تاریخ سه‌شنبه ۶ دسامبر ۲۰۲۲،‏ ۲۱:۵۸ Lessley Dennington <
***@***.***> نوشت:
