### ISSUE TITLE
Drop dependency on `git.exe` executable

### ISSUE THREAD

**Issue by felipecrs** [GitCredentialManager/git-credential-manager#950]
Hi, I don't need Git in Windows since I use WSL2 only for development activity, so I would prefer not to have to install Git on Windows.

I, however, want to use Git Credential Manager from within WSL2 so that I can get a proper authentication handler inside WSL2. Thanks to the WSL2 interoperability between Windows, I can install the Windows version of GCM inside WSL2 following these steps:

1. Extract the following archive to `/usr/local/share/gcm-core`:
   - https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.866/gcm-win-x86-2.0.866.zip
   - Refs https://github.com/GitCredentialManager/git-credential-manager/issues/869
2. `sudo chmod +x /usr/local/share/gcm-core/git-credential-manager-core.exe`
3. `sudo ln -svf /usr/local/share/gcm-core/git-credential-manager-core.exe /usr/local/bin/git-credential-manager-core`
4. `printf '%s\n' '[credential]' 'helper = /usr/local/bin/git-credential-manager-core' 'credentialStore = wincredman' | sudo tee /etc/gitconfig`

However, when executing any git operation which requires authentication, GCM fails with:

```console
❯ git push

Unhandled Exception: System.Exception: Failed to locate 'git.exe' executable on the path.
   at GitCredentialManager.EnvironmentExtensions.LocateExecutable(IEnvironment environment, String program)
   at GitCredentialManager.CommandContext.GetGitPath(IEnvironment environment, IFileSystem fileSystem, ITrace trace)
   at GitCredentialManager.CommandContext..ctor(String appPath)
   at GitCredentialManager.Program.Main(String[] args)
```

Which have one workaround:

1. Install Git for Windows, so GCM under WSL2 can find the `git.exe` binary

But that's exactly what I wanted to avoid, having to install Git on Windows. Do GCM really needs to talk to `git.exe`?

**Comment by felipecrs** [comment]
Ok, I found a better workaround. Based on:

- https://github.com/GitCredentialManager/git-credential-manager/issues/376

I created a shim at `/usr/local/bin/git-credential-manager-core` with:

```bash
#!/bin/bash

set -eu

# Running the Windows version of Git Credential Manager requires
# these additional environment variables as per:
#   https://github.com/GitCredentialManager/git-credential-manager/issues/376
GIT_EXEC_PATH="$(git --exec-path)"
export GIT_EXEC_PATH
export WSLENV="${WSLENV}:GIT_EXEC_PATH/wp"
exec /usr/local/share/gcm-core/git-credential-manager-core.exe "${@}"
```

Which works well!

**Comment by felipecrs** [comment]
I'll be closing this issue for now, but if you have any insight if this could be addressed without requiring the user to set these environment variables, it would be really nice. Thanks anyway!
