### ISSUE TITLE
Simply cannot get GCM to work--GfW simply reverts to legacy auth

### ISSUE THREAD

**Issue by roboaks** [GitCredentialManager/git-credential-manager#979]
### Version

2.0.785+6074e4e3d3

### Operating system

Windows

### OS version or distribution

Windows Server 2008 R2 Datacenter

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

I expect GCM to be invoked but it is not. I am using the GCM bundled with GfW (version 2.38.1.windows.1). 

### Actual behavior

The legacy prompt is displayed:

![image](https://user-images.githubusercontent.com/8267101/205167510-83cb7fc3-ff6e-407a-8ffa-93cb727aff40.png)

### Logs

`git credential-manager-core diagnose` just shows this after 15 minutes:

![image](https://user-images.githubusercontent.com/8267101/205171254-fe0c36f1-d291-4079-9422-989743c85456.png)

So I captured the trace logs:
```
C:\Users\ITP\Documents\GitHub\ITP\ProjectRoots\IIC>git push
17:21:38.307400 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
17:21:38.307400 git.c:460               trace: built-in: git push
17:21:38.307400 run-command.c:655       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/ITS-Data-Services/ITP--ProjectRoots--IIC.git

17:21:38.323000 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
17:21:38.323000 git.c:750               trace: exec: git-remote-https origin https://github.com/ITS-Data-Services/ITP--ProjectRoots--IIC.git
17:21:38.323000 run-command.c:655       trace: run_command: git-remote-https origin https://github.com/ITS-Data-Services/ITP--ProjectRoots--IIC.git
17:21:38.338600 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
17:21:38.385400 run-command.c:655       trace: run_command: bash -c 'cat >/dev/tty && read -r line </dev/tty && echo "$line"'
Username for 'https://github.com': iPaaS-Demonstrator-User
17:22:10.599400 run-command.c:655       trace: run_command: bash -c 'cat >/dev/tty && read -r -s line </dev/tty && echo "$line" && echo >/dev/tty'
Password for 'https://iPaaS-Demonstrator-User@github.com':
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currentl
y recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/ITS-Data-Services/ITP--ProjectRoots--IIC.git/'

C:\Users\ITP\Documents\GitHub\ITP\ProjectRoots\IIC>
```

**Comment by roboaks** [comment]
Here is `etc/gitconfig`:
```
[diff "astextplain"]
	textconv = astextplain
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[http]
	sslBackend = openssl
	sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
[core]
	autocrlf = true
	fscache = true
	symlinks = false
	editor = \"C:\\\\Program Files (x86)\\\\Notepad++\\\\notepad++.exe\" -multiInst -notabbar -nosession -noPlugin
[pull]
	rebase = false
[credential]
	helper = manager-core
[credential "https://dev.azure.com"]
	useHttpPath = true
[init]
	defaultBranch = master
```

Just for grins, I ran `Configure`, which added 
```
[filter "lfs"]
	clean = git-lfs clean %f
	smudge = git-lfs smudge %f
	required = true
[credential]
	helper = 
	helper = C:/Program\\ Files/Git/mingw64/bin/git-credential-manager-core.exe
```
to the user config. But it made no difference.

**Comment by RobertEllisClick55** [comment]
Thank you I’m new too this

**Comment by ldennington** [comment]
@roboaks - when you captured the trace logs above, did you set both `GIT_TRACE` and `GCM_TRACE` or just `GIT_TRACE`?

**Comment by roboaks** [comment]
I set both.

**Comment by roboaks** [comment]
When I ran these commands the first time, they displayed some credentials from Windows Credential Manager (an old GitHub user that was once used on this machine that I don't want to use). After I deleted all the creds from WCM, it did display the browser dialog after displaying this:

![image](https://user-images.githubusercontent.com/8267101/205367209-8e0860ca-86c8-4355-a1b9-3b17ebcf6b7d.png)

Interestingly though, and perhaps this is expected, even after I responded to the dialog (logged into GitHub including entering the token that it sent to my email):

![image](https://user-images.githubusercontent.com/8267101/205367711-1b89c742-d62d-415d-9844-ad76abb8f8cb.png)

it just sat at this prompt and never closed the browser window or changed anything in the command window displayed above.

I thought perhaps deleting the WCM creds might have solved the problem, but when I try to do a Git push, for example, it still prompts for creds in the Git command window. So frustrating and surprising.

**Comment by ldennington** [comment]
GCM looks to be doing its thing when called directly, which means this is likely an issue with Git interop. Just to be sure that everything did work as expected on the GCM side though (given the prompt never changed), it's a good idea to run another `git credential-manager-core get` and verify that you see the correct credentials this time.

Let's also take a look and see if maybe the settings from your system-wide configuration file are being overridden. Please run the following and paste in the output:

`git config --get-all --show-origin credential.helper`

**Comment by roboaks** [comment]
I ran `credential-manager-core get` again and it doesn't appear to have stored the creds:

![image](https://user-images.githubusercontent.com/8267101/205380744-b4ccc9dc-f85b-4edc-8373-c06c07ad2def.png)

I then click `Sign in with your browser`

and it adds:

![image](https://user-images.githubusercontent.com/8267101/205380996-2b4a9ece-ff7d-4625-8dad-14118501ef50.png)

This time it actually let me sign in without needing to send token to email and also allowed me to authorize GCM. But hwne I returned to the command prompt, GCM had added the following:

```
fatal: An error occurred while sending the request.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitCredentialManager.Authentication.OAuth.OAuth2Client.<GetTokenByAuthorizationCodeAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitHub.GitHubAuthentication.<GetOAuthTokenViaBrowserAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitHub.GitHubHostProvider.<GenerateOAuthCredentialAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitHub.GitHubHostProvider.<GenerateCredentialAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitCredentialManager.HostProvider.<GetCredentialAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitCredentialManager.Commands.GetCommand.<ExecuteInternalAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GitCredentialManager.Commands.GitCommandBase.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.CommandHandler.<GetExitCodeAsync>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.<InvokeAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
fatal: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
```
I ran `credential-manager-core get` yet again and it does exactly the same thing: invokes the browser (having not stored the creds), I sign in, close the browser window, and GCM returns the same error stack trace as above.

**Comment by roboaks** [comment]
`git config --get-all --show-origin credential.helper` output:
```
C:\Users\ITP\Documents\GitHub\ITP\ProjectRoots\IIC>git config --get-all --show-origin credential.helper
15:43:08.772200 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
15:43:08.772200 git.c:460               trace: built-in: git config --get-all --show-origin credential.helper
15:43:08.772200 run-command.c:655       trace: run_command: unset GIT_PAGER_IN_USE; LESS=FRX LV=-c less
file:C:/Program Files/Git/etc/gitconfig manager-core
file:C:/Users/ITP/.gitconfig
file:C:/Users/ITP/.gitconfig    C:/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe
file:.git/config
```

**Comment by ldennington** [comment]
Okay, there seems to be an empty helper value in your local config that's overwriting your `manager-core` helper.

We should be able to clean things up by running:

`git config --local --unset credential.helper && git config --global --unset-all credential.helper`

As for the issue with GCM, I believe that could be an incompatibility with OAuth 2.0 and Windows Server 2008 R2 Datacenter (which appears to have reached [EOL in 2020](https://learn.microsoft.com/en-us/troubleshoot/windows-server/windows-server-eos-faq/end-of-support-windows-server-2008-2008r2)). Is there any way you can upgrade your OS? If not, perhaps consider using an [alternative authentication configuration](https://github.com/ldennington/git-credential-manager/blob/main/docs/configuration.md#credentialgithubauthmodes).

**Comment by roboaks** [comment]
The git command did take care of the integration issue. Now, when I `git push`, for example, it does launch the browser as expected. Thank you.

The GCM issue still exists of course. Which alternative auth config would you recommend?

**Comment by ldennington** [comment]
I think `device` will be our best bet. Let me know if it works.

**Comment by roboaks** [comment]
I ran `git config --global credential.gitHubAuthModes "device"` and received this upon trying to push:
```
C:\Users\ITP\Documents\GitHub\ITP\ProjectRoots\IIC>git push
16:23:36.629600 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
16:23:36.629600 git.c:460               trace: built-in: git push
16:23:36.645200 run-command.c:655       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/ITS-Data-Services/ITP--ProjectRoots--IIC.git

16:23:36.692000 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:23:36.707600 git.c:750               trace: exec: git-remote-https origin https://github.com/ITS-Data-Services/ITP--ProjectRoots--IIC.git
16:23:36.707600 run-command.c:655       trace: run_command: git-remote-https origin https://github.com/ITS-Data-Services/ITP--ProjectRoots--IIC.git
16:23:36.848000 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:23:37.035200 run-command.c:655       trace: run_command: 'git credential-manager-core get'
16:23:37.175600 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:23:37.175600 git.c:750               trace: exec: git-credential-manager-core get
16:23:37.175600 run-command.c:655       trace: run_command: git-credential-manager-core get
16:23:37.815200 ...\Application.cs:95   trace: [RunInternalAsync] Version: 2.0.785.29792
16:23:37.830800 ...\Application.cs:96   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
16:23:37.830800 ...\Application.cs:97   trace: [RunInternalAsync] Platform: Windows (x86-64)
16:23:37.830800 ...\Application.cs:98   trace: [RunInternalAsync] OSVersion: 6.1 (build 7601)
16:23:37.830800 ...\Application.cs:99   trace: [RunInternalAsync] AppPath: C:\Program Files\Git\mingw64\bin\git-credential-manager-core.exe
16:23:37.830800 ...\Application.cs:100  trace: [RunInternalAsync] Arguments: get
16:23:38.111600 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'get' command...
16:23:38.127200 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
16:23:38.127200 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   protocol=https
16:23:38.127200 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   host=github.com
16:23:38.236400 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
16:23:38.252000 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
16:23:38.252000 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
16:23:38.267600 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
16:23:38.267600 ...\HostProvider.cs:126 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://github.com account=...
16:23:38.330000 ...\HostProvider.cs:131 trace: [GetCredentialAsync] No existing credentials found.
16:23:38.330000 ...\HostProvider.cs:134 trace: [GetCredentialAsync] Creating new credential...
16:23:38.361200 ...bHostProvider.cs:242 trace: [GetSupportedAuthenticationModesAsync] Supported authentication modes override present: Device
16:23:38.408000 ...pClientFactory.cs:58 trace: [CreateClient] Creating new HTTP client instance...
16:23:38.720000 ...pClientFactory.cs:97 trace: [CreateClient] Custom certificate verification has been enabled with certificate bundle at C:/Program Files/Git/m
ingw64/ssl/certs/ca-bundle.crt
fatal: An error occurred while sending the request.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitCredentialManager.Authentication.OAuth.OAuth2Client.<GetDeviceCodeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitHub.GitHubAuthentication.<GetOAuthTokenViaDeviceCodeAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitHub.GitHubHostProvider.<GenerateOAuthCredentialAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitHub.GitHubHostProvider.<GenerateCredentialAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitCredentialManager.HostProvider.<GetCredentialAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitCredentialManager.Commands.GetCommand.<ExecuteInternalAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GitCredentialManager.Commands.GitCommandBase.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.CommandHandler.<GetExitCodeAsync>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.<InvokeAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
fatal: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
16:23:38.954000 run-command.c:655       trace: run_command: bash -c 'cat >/dev/tty && read -r line </dev/tty && echo "$line"'
Username for 'https://github.com': iPaaS-Demonstrator-User
16:25:21.383600 run-command.c:655       trace: run_command: bash -c 'cat >/dev/tty && read -r -s line </dev/tty && echo "$line" && echo >/dev/tty'
Password for 'https://iPaaS-Demonstrator-User@github.com':
16:25:31.866800 run-command.c:655       trace: run_command: 'git credential-manager-core erase'
16:25:31.898000 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
16:25:31.898000 git.c:750               trace: exec: git-credential-manager-core erase
16:25:31.898000 run-command.c:655       trace: run_command: git-credential-manager-core erase
16:25:32.007200 ...\Application.cs:95   trace: [RunInternalAsync] Version: 2.0.785.29792
16:25:32.022800 ...\Application.cs:96   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
16:25:32.022800 ...\Application.cs:97   trace: [RunInternalAsync] Platform: Windows (x86-64)
16:25:32.022800 ...\Application.cs:98   trace: [RunInternalAsync] OSVersion: 6.1 (build 7601)
16:25:32.022800 ...\Application.cs:99   trace: [RunInternalAsync] AppPath: C:\Program Files\Git\mingw64\bin\git-credential-manager-core.exe
16:25:32.022800 ...\Application.cs:100  trace: [RunInternalAsync] Arguments: erase
16:25:32.085200 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'erase' command...
16:25:32.100800 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
16:25:32.100800 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   protocol=https
16:25:32.100800 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   host=github.com
16:25:32.100800 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   username=iPaaS-Demonstrator-User
16:25:32.100800 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   password=********
16:25:32.178800 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
16:25:32.210000 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
16:25:32.225600 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
16:25:32.225600 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
16:25:32.225600 ...\HostProvider.cs:173 trace: [EraseCredentialAsync] Erasing stored credential in store with service=https://github.com account=iPaaS-Demonstra
tor-User...
16:25:32.288000 ...\HostProvider.cs:180 trace: [EraseCredentialAsync] No credential was erased.
16:25:32.288000 ...GitCommandBase.cs:54 trace: [ExecuteAsync] End 'erase' command...
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currentl
y recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/ITS-Data-Services/ITP--ProjectRoots--IIC.git/'

C:\Users\ITP\Documents\GitHub\ITP\ProjectRoots\IIC>
```

**Comment by ldennington** [comment]
Ah that's my bad. I didn't realize that `device` uses OAuth as well. I think our last recourse here is to try `pat`:

`git config --global credential.gitHubAuthModes "pat"`

You'll also need to [generate a new GitHub Personal Access Token with the `repo` scope checked](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-personal-access-token-classic). GCM will prompt you for this token when you next try to push.

It's possible that authentication via a PAT will require OAuth as well. At that point, I think the best option would be to upgrade your OS if that's in any way possible or to consider switching to [SSH authentication](https://docs.github.com/en/authentication/connecting-to-github-with-ssh).

**Comment by roboaks** [comment]
Didn't work due to same issue.

I finally got it working under SSH.

What a PITA this was (not your fault of course).

Fortunately, these are old AWS demo boxes for our platform and probably the last remaining Server 2008 instances in our fleet.

**Comment by ldennington** [comment]
Yes indeed. I'm sorry you've had to deal with this. Hopefully you'll be able to retire those old instances soon.
